<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFMaw3Nd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFMaw3Nd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFMaw3Nd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFMaw3Nd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFMaw3Nd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FMaw3Nd',
    'container.build_id' => '3ae01ddb',
    'container.build_time' => 1526075098,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFMaw3Nd');
